sudo: false

language: node_js

node_js:
  - "8"

notifications:
  disabled: true

before_install:
  - npm install -g npm@5

env:
  - TEST_DIR=browser
  - TEST_DIR=server

install:
  - npm install -g codecov
  - npm install --prefix browser
  - npm install --prefix server

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - cd $TEST_DIR
  - npm test
  - codecov
