name: Test
"on":
  push:
    branches:
      - metadata
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install --no-package-lock
  
      - name: Run tests
        run: npm test
